name: examples

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Install apt-get packages
      run: |
        sudo ACCEPT_EULA=Y apt-get update
        sudo ACCEPT_EULA=Y apt-get upgrade
        sudo apt-get install wget git curl software-properties-common build-essential
        
    - name: Install Rust target
      run: |
        rustup target add wasm32-wasi
        cargo install cargo-wasi
        
    - name: Install WasmEdge
      run: |
        curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | sudo bash -s -- -p /usr/local

    - name: Install WasmEdge HTTPS REQ plugin
      run : |
        wget https://github.com/WasmEdge/WasmEdge/releases/download/0.11.1/WasmEdge-plugin-wasmedge_httpsreq-0.11.1-ubuntu20.04_x86_64.tar.gz
        tar -xzf WasmEdge-plugin-wasmedge_httpsreq-0.11.1-ubuntu20.04_x86_64.tar.gz
        sudo cp *.so /usr/local/lib/wasmedge/

    - name: add_headers
      run: |
        cargo wasi build --release --example add_headers
        wasmedge target/wasm32-wasi/release/examples/add_headers.wasm
    
    - name: get
      run: |
        cargo wasi build --release --example get
        wasmedge target/wasm32-wasi/release/examples/get.wasm
        
    - name: get https
      run: |
        cargo wasi build --release --example get_https
        wasmedge target/wasm32-wasi/release/examples/get_https.wasm

    - name: head
      run: |
        cargo wasi build --release --example head
        wasmedge target/wasm32-wasi/release/examples/head.wasm
        
    - name: head https
      run: |
        cargo wasi build --release --example head_https
        wasmedge target/wasm32-wasi/release/examples/head_https.wasm

    - name: post
      run: |
        cargo wasi build --release --example post
        wasmedge target/wasm32-wasi/release/examples/post.wasm
        
    - name: post https
      run: |
        cargo wasi build --release --example post_https
        wasmedge target/wasm32-wasi/release/examples/post_https.wasm
     
